[package]
name = "flapper"
version = "0.4.3"
edition = "2021"
authors = ["Jan-Simon Baudler <janbaudler@gmail.com"]

[dependencies]
actix-web = "4"
env_logger = "0.10.0"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
